[build-system]
requires = ["setuptools>=42", "wheel", "pybind11", "cibuildwheel"]
build-backend = "setuptools.build_meta"
[tool.cibuildwheel]
skip = "cp27-*"
build = "cp36-* cp37-* cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
archs = "auto"