[build-system]
requires = ["setuptools>=42", "setuptools_scm", "wheel", "pybind11", "cibuildwheel"]
build-backend = "setuptools.build_meta"
[tool.cibuildwheel]
skip = "cp27-* cp36-*"
build = "cp38-* cp39-* cp310-* cp311-* cp312-*"
archs = "auto"