# {% set version = load_file_data("polsartools/version.json")["version"] %}

package:
  name: polsartools
  version: "0.7"

source:
  path: ..  

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python {{ python }}
    - {{ compiler('cxx') }}  # C++ compiler
  host:
    - python {{ python }}
    - pip
    - pybind11
    - h5py
    - setuptools
    - wheel
  run:
    - python  {{ python }}
    - pip
    - numpy
    - scipy
    - click
    - tqdm
    - matplotlib
    - pybind11
    - h5py
    - scikit-image
    - gdal

test:
  # Include tests to validate the build
  commands:
    - python -c "import polsartools"

about:
  home: https://github.com/Narayana-Rao/polsartools
  license: GPL-3.0
  summary: "A python package for processing Polarimetric Synthetic Aperture Radar (PolSAR) data."
