# {% set version = load_file_data("polsartools/version.json")["version"] %}
{% set linux = target_platform.startswith('linux') %}

package:
  name: polsartools
  version: "0.7"

source:
  path: ..  

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python {{ python }}
    {% if linux %}
    - {{ compiler('cxx') }}
    - libstdcxx-ng >=13
    {% endif %}
  host:
    - python {{ python }}
    - pip
    - pybind11
    - h5py
    {% if linux %}
    - libstdcxx-ng >=13
    {% endif %}
  run:
    - python  {{ python }}
    - pip
    - numpy
    - scipy
    - click
    - tqdm
    - matplotlib
    - pybind11
    - h5py
    - scikit-image
    - gdal
    {% if linux %}
    - libstdcxx-ng >=13
    {% endif %}

test:
  # Include tests to validate the build
  commands:
    - python -c "import polsartools"

about:
  home: https://github.com/Narayana-Rao/polsartools
  license: GPL-3.0
  summary: "A python package for processing Polarimetric Synthetic Aperture Radar (PolSAR) data."
