
package:
  name: polsartools
  version: "0.8"

source:
  path: ..  

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pybind11
    - setuptools
    - wheel
    - conda-build  
    - gdal         
    - anaconda-client
  run:
    - python
    - pip
    - numpy
    - scipy
    - click
    - tqdm
    - matplotlib
    - pybind11  
    - tables
    - netcdf4
    - scikit-image
    - gdal  

test:
  commands:
    - python -c "import polsartools"

about:
  home: https://github.com/Narayana-Rao/polsartools
  license: GPL-3.0
  summary: "A python package for processing Polarimetric Synthetic Aperture Radar (PolSAR) data."

# platforms:
#   - linux
#   - osx
#   - win