name: Build

on: 
  push:
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Set up Miniconda for Conda build
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-activate-base: false
        python-version: ${{ matrix.python-version }}

    - name: Install Conda dependencies
      run: |
        conda install -y conda-build anaconda-client  # Install Conda build tools

    # Install GDAL system dependencies based on the OS
    - name: Install GDAL system dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install -y gdal-bin libgdal-dev

    - name: Install GDAL system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install gdal
        brew upgrade gdal

    - name: Install GDAL system dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        pip install GDAL

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install .  

    - name: Build Conda package
      run: |
        conda build ./conda-recipe  # Adjust path to your conda recipe folder

    # - name: Upload package to Anaconda Cloud
    #   run: |
    #     conda config --add channels conda-forge
    #     conda config --set anaconda_upload yes
    #     anaconda upload /path/to/your/package.tar.bz2 --user <your-anaconda-username>  # Replace with actual package path and Anaconda username

    - name: Test with pytest
      run: |
        cd tests
        python -m pytest -v tests.py
